- name: install kubernetes
  dnf: name=kubernetes state=latest
- name: add kubernetes config
  template:
    src: etc-kubernetes-config.j2
    dest: /etc/kubernetes/config
    backup: yes
- name: create directory for certificate
  file:
    path: /etc/kubernetes/ssl
    state: directory
- name: copy apiserver certificate
  copy:
    src: certs/kubernetes-apiserver.crt
    dest: /etc/kubernetes/ssl/apiserver.crt
    owner: kube
    group: kube
    mode: u=rw,go=r
- name: copy client CA
  copy:
    src: certs/ca.crt
    dest: /etc/kubernetes/ssl/
