- name: add kubelet base config
  template:
    src: etc-kubernetes-kubelet.j2
    dest: /etc/kubernetes/kubelet
  notify: restart kubelet
- name: add kubelet kubeconfig
  template:
    src: etc-kubernetes-kubeconfig.j2
    dest: /etc/kubernetes/kubeconfig
  notify: restart kubelet
- name: add client certificate
  copy:
    src: "certs/{{ ansible_hostname }}-kubernetes-client.crt"
    dest: "/etc/kubernetes/ssl/{{ ansible_hostname }}-client.crt"
  notify: restart kubelet
- name: add client certificate key
  copy:
    src: "certs/{{ ansible_hostname }}-kubernetes-client.key"
    dest: "/etc/kubernetes/ssl/{{ ansible_hostname }}-client.key"
    owner: kube
    group: kube
    mode: u=rw,go=
  notify: restart kubelet
- name: start kube-proxy
  service:
    name: kube-proxy
    enabled: true
    state: started
- name: start kubelet
  service:
    name: kubelet
    enabled: true
    state: started
- name: start docker
  service:
    name: docker
    enabled: true
    state: started
