apiVersion: batch/v1
kind: Job
metadata:
  name: planner-worker-$LOWERDOMAIN-$LOWERPROBLEM
  labels:
    jobgroup: planning-tasks
spec:
  template:
    metadata:
      name: planner-worker
    spec:
      containers:
      - name: planner-worker
        image: morxa/planner
        command: ["worker.py"]
        args: ["$DOMAIN", "$PROBLEM"]
        volumeMounts:
          - name: mongo-certs
            mountPath: /secrets/mongo-certs
            readOnly: true
        env:
          - name: PLANDB_USER
            valueFrom:
              secretKeyRef:
                name: plan-db
                key: dbuser.txt
          - name: PLANDB_PWD
            valueFrom:
              secretKeyRef:
                name: plan-db
                key: pwd.txt
          - name: PLANDB_HOST
            value: enterprise
        resources:
          requests:
            cpu: "1"
            memory: "8G"
          limits:
            cpu: "1"
            memory: "8G"
      volumes:
        - name: mongo-certs
          secret:
            secretName: mongo-certs
      restartPolicy: Never
