apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 5672
    nodePort: 30672
  selector:
    app: taskQueue
    component: rabbitmq
